# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_auto_20171009_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
