# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
